"""Add senha and categoria to usuarios

Revision ID: 24b32f1743bf
Revises: b83bdadde5e1
Create Date: 2026-06-08 14:35:31.113741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b32f1743bf'
down_revision: Union[str, Sequence[str], None] = 'b83bdadde5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('usuarios', 'categoria_id')
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###
